### ISSUE TITLE
Unable to run Drush command after using this package to replace BLT

### ISSUE THREAD

**Issue by aneek** [acquia/drupal-recommended-settings#45]
**Describe the bug**
When using this package to replace BLT in a Lando development environment, Drush 11.6 and Drush 12 encountered FATAL error.

**To Reproduce**
Replace BLT with this package with Lando

**Expected behavior**
Drush command should run properly or `lando setup` should run properly.

**Error Message**
```
www-data@f44f7962e95a:/app$ /app/vendor/bin/drush 

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Acquia\Drupal\RecommendedSettings\Drush\Commands\MultisiteDrushCommands::__construct(), 0 passed and exactly 1 expected in /app/vendor/acquia/drupal-recommended-settings/src/Drush/Commands/MultisiteDrushCommands.php on line 34

ArgumentCountError: Too few arguments to function Acquia\Drupal\RecommendedSettings\Drush\Commands\MultisiteDrushCommands::__construct(), 0 passed and exactly 1 expected in /app/vendor/acquia/drupal-recommended-settings/src/Drush/Commands/MultisiteDrushCommands.php on line 34

Call Stack:
    0.0041     434792   1. {main}() /app/vendor/bin/drush:0
    0.0053     435360   2. include('/app/vendor/drush/drush/drush') /app/vendor/bin/drush:119
    0.0062     446808   3. require('/app/vendor/drush/drush/drush.php') /app/vendor/drush/drush/drush:4
    0.0568    2250272   4. Drush\Runtime\Runtime->run($argv = [0 => '/app/vendor/bin/drush']) /app/vendor/drush/drush/drush.php:79
   ......
 [warning] Drush command terminated abnormally.
```
![Screenshot-2024-03-18-000977](https://github.com/acquia/drupal-recommended-settings/assets/584583/cd2666e6-171c-438b-8e5c-16d9ab7bac7b)

Screenshot attached.

**Comment by jacqui1811** [comment]
Having the same problem. 
Would be grateful if someone could assist.

**Comment by aneek** [comment]
Any update on this? if this can be fixed? In lando and also in ddev both the drush commands are failing.

**Comment by jacqui1811** [comment]
Hi.

Can you do a patch rather than a merge please ?
I am not clear on how to handle the merges and get them applied to various acquia environments.

**Comment by jacqui1811** [comment]
Just want to comment that I did a composer update, it got that merge and Drush is now working again.
Thank you for your prompt response.
