### ISSUE TITLE
drs/config.yml or docroot/sites/[site_name]/dr/config.yml not respected when running `drush settings`

### ISSUE THREAD

**Issue by pookmish** [acquia/drupal-recommended-settings#69]
**Describe the bug**
When cloning a project or setting up a new project, the `drush settings` command does not respect the configured database credentials. It always defaults to the values from `vendor/acquia/drupal-recommended-settings/config/build.yml`

**To Reproduce**
1. create a new project like Drupal 11
2. Add the `acquia/drupal-recommended-settings` dependency
3. create a `drs/config.yml` file with desired database credentials
4. run `drush settings`
5. verify your desired credentials are not respected with `drush sql-connect`

**Expected behavior**
Database config is applied to the local.settings.php

**Screenshots**

**Environment**
Local

**Additional context**

**Comment by vishalkhode1** [comment]
Thanks for reporting the issue. Requested some changes on [!70](https://github.com/acquia/drupal-recommended-settings/pull/70).

**Comment by vishalkhode1** [comment]
Thanks. Closing as it's merged: https://github.com/acquia/drupal-recommended-settings/pull/78.
