### ISSUE TITLE
Add support For Drush 13.

### ISSUE THREAD

**Issue by arjak-dev** [acquia/drupal-recommended-settings#79]
**Is your feature request related to a problem? Please describe.**
We have to add support for drush 13 which is required for Drupal 11. 

**Describe the solution you'd like**
Update Drush 13 in the composer.json file

**Additional context**
Composer dependency update for Drush

**Comment by vishalkhode1** [comment]
This is released as part of [1.1.0](https://github.com/acquia/drupal-recommended-settings/releases/tag/1.1.0).
